//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCalcService.ServiceCalculator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.CompositeItem[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GuidValue {
            get {
                return this.GuidValueField;
            }
            set {
                if ((this.GuidValueField.Equals(value) != true)) {
                    this.GuidValueField = value;
                    this.RaisePropertyChanged("GuidValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.CompositeItem[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeItem", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GuidValue {
            get {
                return this.GuidValueField;
            }
            set {
                if ((this.GuidValueField.Equals(value) != true)) {
                    this.GuidValueField = value;
                    this.RaisePropertyChanged("GuidValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class ReceiptInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.CargoUnitInfo[] CargoUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CityFromIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityFromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CityToIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<TestCalcService.ServiceCalculator.DelivType> DeliveryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveWHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendWHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ServiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.CargoUnitInfo[] CargoUnits {
            get {
                return this.CargoUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoUnitsField, value) != true)) {
                    this.CargoUnitsField = value;
                    this.RaisePropertyChanged("CargoUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CityFromID {
            get {
                return this.CityFromIDField;
            }
            set {
                if ((this.CityFromIDField.Equals(value) != true)) {
                    this.CityFromIDField = value;
                    this.RaisePropertyChanged("CityFromID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityFromName {
            get {
                return this.CityFromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityFromNameField, value) != true)) {
                    this.CityFromNameField = value;
                    this.RaisePropertyChanged("CityFromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CityToID {
            get {
                return this.CityToIDField;
            }
            set {
                if ((this.CityToIDField.Equals(value) != true)) {
                    this.CityToIDField = value;
                    this.RaisePropertyChanged("CityToID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityToName {
            get {
                return this.CityToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityToNameField, value) != true)) {
                    this.CityToNameField = value;
                    this.RaisePropertyChanged("CityToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Days {
            get {
                return this.DaysField;
            }
            set {
                if ((this.DaysField.Equals(value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TestCalcService.ServiceCalculator.DelivType> DeliveryType {
            get {
                return this.DeliveryTypeField;
            }
            set {
                if ((this.DeliveryTypeField.Equals(value) != true)) {
                    this.DeliveryTypeField = value;
                    this.RaisePropertyChanged("DeliveryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveWH {
            get {
                return this.ReceiveWHField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveWHField, value) != true)) {
                    this.ReceiveWHField = value;
                    this.RaisePropertyChanged("ReceiveWH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendWH {
            get {
                return this.SendWHField;
            }
            set {
                if ((object.ReferenceEquals(this.SendWHField, value) != true)) {
                    this.SendWHField = value;
                    this.RaisePropertyChanged("SendWH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ServiceID {
            get {
                return this.ServiceIDField;
            }
            set {
                if ((this.ServiceIDField.Equals(value) != true)) {
                    this.ServiceIDField = value;
                    this.RaisePropertyChanged("ServiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargoUnitInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class CargoUnitInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentWHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentWH {
            get {
                return this.CurrentWHField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentWHField, value) != true)) {
                    this.CurrentWHField = value;
                    this.RaisePropertyChanged("CurrentWH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelivType", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    public enum DelivType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warehouse = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Door = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warehouse_Warehouse = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warehouse_Door = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Door_Warehouse = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Door_Door = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelCountrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelMainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelSMSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelCountrycode {
            get {
                return this.TelCountrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TelCountrycodeField, value) != true)) {
                    this.TelCountrycodeField = value;
                    this.RaisePropertyChanged("TelCountrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelMain {
            get {
                return this.TelMainField;
            }
            set {
                if ((object.ReferenceEquals(this.TelMainField, value) != true)) {
                    this.TelMainField = value;
                    this.RaisePropertyChanged("TelMain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelSMS {
            get {
                return this.TelSMSField;
            }
            set {
                if ((object.ReferenceEquals(this.TelSMSField, value) != true)) {
                    this.TelSMSField = value;
                    this.RaisePropertyChanged("TelSMS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptCollection", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class ReceiptCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.ReceiptInfo[] ReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.ReceiptInfo[] Receipts {
            get {
                return this.ReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptsField, value) != true)) {
                    this.ReceiptsField = value;
                    this.RaisePropertyChanged("Receipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeographyCollection", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class GeographyCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.GeographyInfo[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.GeographyInfo[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeographyInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class GeographyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.WarehouseCollection WarehousesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indexes {
            get {
                return this.IndexesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexesField, value) != true)) {
                    this.IndexesField = value;
                    this.RaisePropertyChanged("Indexes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.WarehouseCollection Warehouses {
            get {
                return this.WarehousesField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehousesField, value) != true)) {
                    this.WarehousesField = value;
                    this.RaisePropertyChanged("Warehouses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseCollection", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class WarehouseCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.WarehouseInfo[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.WarehouseInfo[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class WarehouseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityAddress {
            get {
                return this.CityAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CityAddressField, value) != true)) {
                    this.CityAddressField = value;
                    this.RaisePropertyChanged("CityAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicesCollection", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class ServicesCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCalcService.ServiceCalculator.ServiceInfo[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCalcService.ServiceCalculator.ServiceInfo[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackingWCF")]
    [System.SerializableAttribute()]
    public partial class ServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCalculator.ITrackingService")]
    public interface ITrackingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetData", ReplyAction="http://tempuri.org/ITrackingService/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetData", ReplyAction="http://tempuri.org/ITrackingService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetDataByValue", ReplyAction="http://tempuri.org/ITrackingService/GetDataByValueResponse")]
        string GetDataByValue(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetDataByValue", ReplyAction="http://tempuri.org/ITrackingService/GetDataByValueResponse")]
        System.Threading.Tasks.Task<string> GetDataByValueAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetDataByContract", ReplyAction="http://tempuri.org/ITrackingService/GetDataByContractResponse")]
        string GetDataByContract(TestCalcService.ServiceCalculator.CompositeType value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetDataByContract", ReplyAction="http://tempuri.org/ITrackingService/GetDataByContractResponse")]
        System.Threading.Tasks.Task<string> GetDataByContractAsync(TestCalcService.ServiceCalculator.CompositeType value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetContractDataByValue", ReplyAction="http://tempuri.org/ITrackingService/GetContractDataByValueResponse")]
        TestCalcService.ServiceCalculator.CompositeType GetContractDataByValue(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetContractDataByValue", ReplyAction="http://tempuri.org/ITrackingService/GetContractDataByValueResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.CompositeType> GetContractDataByValueAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetReceiptData", ReplyAction="http://tempuri.org/ITrackingService/GetReceiptDataResponse")]
        TestCalcService.ServiceCalculator.ReceiptInfo GetReceiptData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetReceiptData", ReplyAction="http://tempuri.org/ITrackingService/GetReceiptDataResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ReceiptInfo> GetReceiptDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetClientData", ReplyAction="http://tempuri.org/ITrackingService/GetClientDataResponse")]
        TestCalcService.ServiceCalculator.ClientInfo GetClientData(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetClientData", ReplyAction="http://tempuri.org/ITrackingService/GetClientDataResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ClientInfo> GetClientDataAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetClientSentReceipts", ReplyAction="http://tempuri.org/ITrackingService/GetClientSentReceiptsResponse")]
        TestCalcService.ServiceCalculator.ReceiptCollection GetClientSentReceipts(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetClientSentReceipts", ReplyAction="http://tempuri.org/ITrackingService/GetClientSentReceiptsResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ReceiptCollection> GetClientSentReceiptsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetGeography", ReplyAction="http://tempuri.org/ITrackingService/GetGeographyResponse")]
        TestCalcService.ServiceCalculator.GeographyCollection GetGeography(string searchPattern, TestCalcService.ServiceCalculator.DelivType deliveryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetGeography", ReplyAction="http://tempuri.org/ITrackingService/GetGeographyResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.GeographyCollection> GetGeographyAsync(string searchPattern, TestCalcService.ServiceCalculator.DelivType deliveryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetWarehouse", ReplyAction="http://tempuri.org/ITrackingService/GetWarehouseResponse")]
        TestCalcService.ServiceCalculator.WarehouseCollection GetWarehouse(string searchPattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetWarehouse", ReplyAction="http://tempuri.org/ITrackingService/GetWarehouseResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.WarehouseCollection> GetWarehouseAsync(string searchPattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetServices", ReplyAction="http://tempuri.org/ITrackingService/GetServicesResponse")]
        TestCalcService.ServiceCalculator.ServicesCollection GetServices(string searchPattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/GetServices", ReplyAction="http://tempuri.org/ITrackingService/GetServicesResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ServicesCollection> GetServicesAsync(string searchPattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/CalculateReceipt", ReplyAction="http://tempuri.org/ITrackingService/CalculateReceiptResponse")]
        TestCalcService.ServiceCalculator.ReceiptCollection CalculateReceipt(TestCalcService.ServiceCalculator.ReceiptInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingService/CalculateReceipt", ReplyAction="http://tempuri.org/ITrackingService/CalculateReceiptResponse")]
        System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ReceiptCollection> CalculateReceiptAsync(TestCalcService.ServiceCalculator.ReceiptInfo value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrackingServiceChannel : TestCalcService.ServiceCalculator.ITrackingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrackingServiceClient : System.ServiceModel.ClientBase<TestCalcService.ServiceCalculator.ITrackingService>, TestCalcService.ServiceCalculator.ITrackingService {
        
        public TrackingServiceClient() {
        }
        
        public TrackingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrackingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public string GetDataByValue(string value) {
            return base.Channel.GetDataByValue(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataByValueAsync(string value) {
            return base.Channel.GetDataByValueAsync(value);
        }
        
        public string GetDataByContract(TestCalcService.ServiceCalculator.CompositeType value) {
            return base.Channel.GetDataByContract(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataByContractAsync(TestCalcService.ServiceCalculator.CompositeType value) {
            return base.Channel.GetDataByContractAsync(value);
        }
        
        public TestCalcService.ServiceCalculator.CompositeType GetContractDataByValue(string value) {
            return base.Channel.GetContractDataByValue(value);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.CompositeType> GetContractDataByValueAsync(string value) {
            return base.Channel.GetContractDataByValueAsync(value);
        }
        
        public TestCalcService.ServiceCalculator.ReceiptInfo GetReceiptData(string value) {
            return base.Channel.GetReceiptData(value);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ReceiptInfo> GetReceiptDataAsync(string value) {
            return base.Channel.GetReceiptDataAsync(value);
        }
        
        public TestCalcService.ServiceCalculator.ClientInfo GetClientData(string email) {
            return base.Channel.GetClientData(email);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ClientInfo> GetClientDataAsync(string email) {
            return base.Channel.GetClientDataAsync(email);
        }
        
        public TestCalcService.ServiceCalculator.ReceiptCollection GetClientSentReceipts(string email) {
            return base.Channel.GetClientSentReceipts(email);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ReceiptCollection> GetClientSentReceiptsAsync(string email) {
            return base.Channel.GetClientSentReceiptsAsync(email);
        }
        
        public TestCalcService.ServiceCalculator.GeographyCollection GetGeography(string searchPattern, TestCalcService.ServiceCalculator.DelivType deliveryType) {
            return base.Channel.GetGeography(searchPattern, deliveryType);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.GeographyCollection> GetGeographyAsync(string searchPattern, TestCalcService.ServiceCalculator.DelivType deliveryType) {
            return base.Channel.GetGeographyAsync(searchPattern, deliveryType);
        }
        
        public TestCalcService.ServiceCalculator.WarehouseCollection GetWarehouse(string searchPattern) {
            return base.Channel.GetWarehouse(searchPattern);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.WarehouseCollection> GetWarehouseAsync(string searchPattern) {
            return base.Channel.GetWarehouseAsync(searchPattern);
        }
        
        public TestCalcService.ServiceCalculator.ServicesCollection GetServices(string searchPattern) {
            return base.Channel.GetServices(searchPattern);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ServicesCollection> GetServicesAsync(string searchPattern) {
            return base.Channel.GetServicesAsync(searchPattern);
        }
        
        public TestCalcService.ServiceCalculator.ReceiptCollection CalculateReceipt(TestCalcService.ServiceCalculator.ReceiptInfo value) {
            return base.Channel.CalculateReceipt(value);
        }
        
        public System.Threading.Tasks.Task<TestCalcService.ServiceCalculator.ReceiptCollection> CalculateReceiptAsync(TestCalcService.ServiceCalculator.ReceiptInfo value) {
            return base.Channel.CalculateReceiptAsync(value);
        }
    }
}
